import type {Metadata} from "next"
import {Inter} from "next/font/google"
import "./globals.css"
import {twMerge} from "tailwind-merge"
const inter = Inter({subsets: ["latin"]})
import {EdgeStoreProvider} from "../lib/edgestore"

export const metadata: Metadata = {
  title: "BEDROCK",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-dark.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          "min-h-screen  bg-dark-blue overflow-x-hidden ",
          inter.className
        )}
      >
        <div className="">
          <EdgeStoreProvider>
          {children}
          </EdgeStoreProvider>
          </div>
      </body>
    </html>
  )
}
