name: Deploy Next.js Application
on:
 push:
    branches:
      - main

jobs: 
 build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env
        run: echo "NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}" >>.env && echo "EDGE_STORE_ACCESS_KEY=${{ secrets.EDGE_STORE_ACCESS_KEY }}" >>.env && echo "EDGE_STORE_SECRET_KEY=${{ secrets.EDGE_STORE_SECRET_KEY }}" >>.env && echo "NEXT_PUBLIC_LIVEBLOCKS_KEY=${{ secrets.NEXT_PUBLIC_LIVEBLOCKS_KEY }}" >>.env && echo "NEXT_PRIVATE_LIVEBLOCKS_KEY=${{ secrets.NEXT_PRIVATE_LIVEBLOCKS_KEY }}" >>.env && echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" >>.env 
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t ashif091/bedrock-client  .  
      - name: Publish Image to Docker Hub
        run: docker push ashif091/bedrock-client:latest
 deploy:
    needs: build 
    runs-on: self-hosted 
    steps: 
      - name: Delete old container
        run: docker rm -f frontend-container  
      - name: Delete Used Docker Objects
        run: docker system prune  -f
      - name: Remove all unused images (both dangling and unreferenced)
        run: docker image prune -a -f
      - name: Pull image from Docker Hub
        run: docker pull ashif091/bedrock-client:latest
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 --name frontend-container ashif091/bedrock-client
